# Generated by Django 4.2.2 on 2023-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todoitem_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
