# Generated by Django 4.2.2 on 2023-08-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todoitem_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
